### ISSUE TITLE
Add Python 3.5 support

### ISSUE THREAD

**Issue by hnykda** [wiseio/paratext#13]
As mentioned [here](https://github.com/wiseio/paratext/issues/10), there is lack of support for Python 3.5. We all know about Python 2 vs. Python 3, but with simple project like this it should be very easy to port it to something which has its future. Furthermore, you say `Python (2.7 or above)` in README.

There are e.g. `xrange` at https://github.com/wiseio/paratext/blob/master/python/paratext/core.py#L192, which won't work on Python 3. I am willing to help here - is there any specific reason why not to use Python 2 and Python 3? I would recommend using shared codebase with `__future__` or `six` package.

Thanks

**Comment by deads** [comment]
Hi,

Thanks for your interest in ParaText. The "2.7 and above" is a typo. There is no specific reason to not support both except I have yet to use Python 3. I am happy to help in any way to add support for it.

I have taken a stab at adapting the C/C++ code to Python3. It compiles. Now, the next task is to adapt the Python code.

**Comment by hnykda** [comment]
Hey! Thanks for the answer. I will try to take a look at it next week.

**Comment by deads** [comment]
Hi,

I've adapted the Python code. ParaText appears to work on Python3. Please see the `paratext-2016-06-python3-support` branch.

Best,
Damian

**Comment by wesm** [comment]
@deads I added https://github.com/wiseio/paratext/issues/21 to help with maintaining 2/3 compatibility

**Comment by hnykda** [comment]
Hey. Great, is there anything we might contribute to regarding Python 3 compat?

**Comment by deads** [comment]
It's been merged into master. I'll go and close this issue.
