### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by chris-b1** [wiseio/paratext#24]
I started looking at this, the only substantive change that seems to be necessary is removing the use of VLAs (e.g. [here](https://github.com/wiseio/paratext/blob/master/src/csv/colbased_worker.hpp#L89)) - would you accept a PR replacing them with `std::vector<char>`?

`unistd.h` is also included in several places, which isn't available on Windows, but it doesn't look anything is actually used from it?

**Comment by wesm** [comment]
Can you use `alloca` (assuming that you're sure you're not going to overflow the stack) for VLAs?

**Comment by chris-b1** [comment]
Yes - if it's preferred to keep those buffers stack allocated, MSVC provides an [`_alloca` ](https://msdn.microsoft.com/en-us/library/wb1s57t5.aspx) that could be used.

**Comment by JamesRamm** [comment]
More work required for windows support than this I think...looks like it uses `unistd.h` which isnt available under windows and also `pthreads`

**Comment by deads** [comment]
This issue should be resolved by the PR #54, #44, #38, which have been merged into master. Thank you for your contributions.
