### ISSUE TITLE
Receiving Error when installing on Windows 7

### ISSUE THREAD

**Issue by TheTrette** [wiseio/paratext#37]
Newbie here, came across paratext via a google search on processing large .cvs files to pandas DataFrames. I've followed the directions, but when I get to the command "python setup.py build install", I keep receiving this error: 

(C:\Users\mtrette\AppData\Local\Continuum\Anaconda3\envs\ParaText) c:\User
tte\paratext\python>python setup.py build install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    p = subprocess.Popen(["which", "swig"])
  File "C:\Users\mtrette\AppData\Local\Continuum\Anaconda3\envs\ParaText\l
process.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\mtrette\AppData\Local\Continuum\Anaconda3\envs\ParaText\l
process.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Like I said, I'm a newbie so not sure exactly what is going on, was hoping that someone may be able to shed some light and help me out. Thank you! By the way, I've completed the steps using the "normal" (ie not via Anaconda) cmd prompt and got the same error message.

**Comment by JamesRamm** [comment]
looks like the error is coming from trying to call `swig`.
Can you check that:
1. You have `swig` installed?
2. It is available on your system `PATH`?

You should be able to install swig with `conda install swig`

**Comment by JamesRamm** [comment]
You can ignore my above comment.
It is not `swig` that is the problem but `which`...the `which` program is not available on windows...using the `where` command would be the windows equivalent...

**Comment by TheTrette** [comment]
Thank you to JamesRamm for the suggestion, this resolved the issue. For future googlers, I had to update to Microsoft Visual Studio 2015, and include the Common Tools for Visual C++2015 feature to get past the vsvarsall.dat error. I just ran into another error which I'm troubleshooting, so getting closer.

**Comment by JamesRamm** [comment]
@TheTrette you might want to look at #38 which has got to the point of successful compile but is having runtime issues
