### ISSUE TITLE
Build fails on Windows 7 with Anaconda

### ISSUE THREAD

**Issue by ianlcassidy** [wiseio/paratext#43]
I am having issues building this package.  Here's what I've got installed:
- Python 2.7.12 :: Anaconda 4.1.1 (64-bit)
- gcc.exe (GCC) 4.9.3
- SWIG Version 3.0.10
  Compiled with i686-w64-mingw32-g++ [i686-w64-mingw32]
  Configured options: +pcre

This is the output I get when I try to build:

`
$ python setup.py build install
/c/Users/icassidy/AppData/Local/Continuum/Anaconda2/Library/bin/swig
..\src\diagnostic\parse_and_sum.hpp(158) : Warning 302: Identifier 'parse_token' redefined (ignored),
..\src\diagnostic\parse_and_sum.hpp(129) : Warning 302: previous definition of 'parse_token'.
0.2.1rc1
('running swig: ', ['swig', '-c++', '-python', '-I../src/', '-outdir', './', '../src/paratext_internal.i'])
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building py_modules sources
building extension "_paratext_internal" sources
build_src: building npy-pkg config files
running build_py
copying paratext_internal.py -> build\lib.win-amd64-2.7
copying paratext\__init__.py -> build\lib.win-amd64-2.7\paratext
running build_ext
customize MSVCCompiler
customize MSVCCompiler using build_ext
customize MSVCCompiler
Missing compiler_cxx fix for MSVCCompiler
customize MSVCCompiler using build_ext
building '_paratext_internal' extension
compiling C sources
C:\Users\icassidy\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I../src/ -IC:\Users\icassidy\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\icassidy\AppData\Local\Continuum\Anaconda2\include -IC:\Users\icassidy\AppData\Local\Continuum\Anaconda2\PC /Tp../src/paratext_internal_wrap.cxx /Fobuild\temp.win-amd64-2.7\Release\../src/paratext_internal_wrap.obj -std=c++11 -Wall -Wextra -pthread /Zm1000
Found executable C:\Users\icassidy\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe
C:\Users\icassidy\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
cl : Command line error D8021 : invalid numeric argument '/Wextra'
error: Command "C:\Users\icassidy\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I../src/ -IC:\Users\icassidy\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\icassidy\AppData\Local\Continuum\Anaconda2\include -IC:\Users\icassidy\AppData\Local\Continuum\Anaconda2\PC /Tp../src/paratext_internal_wrap.cxx /Fobuild\temp.win-amd64-2.7\Release\../src/paratext_internal_wrap.obj -std=c++11 -Wall -Wextra -pthread /Zm1000" failed with exit status 2
`

Please help!

**Comment by ianlcassidy** [comment]
Do I have the wrong version of SWIG installed?

**Comment by batterseapower** [comment]
It looks to me like this will be fixed by PR #44

**Comment by deads** [comment]
This should be resolved in the latest master. If not, please reopen the issue.
