### ISSUE TITLE
Initial release for a conda-forge pkg

### ISSUE THREAD

**Issue by danielfrg** [wiseio/paratext#9]
Thanks for the library it looks great! I would like to have a conda pkg that people can install based on conda-forge. I have started that work here: https://github.com/conda-forge/staged-recipes/pull/731

The only thing needed is an "official" release with a git tag that I can use to freeze the build of the pkg.

Also, would someone want to be added as a maintainer for that conda pkg? If not I am ok doing that.

Thanks!

**Comment by deads** [comment]
Hi Daniel,

Thank you for your help. It would be great to bundle paratext in a conda package. I will create a tag for the official release. As you are with continuum, I am fine with you being the maintainer for conda.

Best,
Damian

**Comment by wesm** [comment]
@danielfrg i'm happy to volunteer to help w/ maintainership of the conda-forge recipe

**Comment by danielfrg** [comment]
Great. Note that this is a conda-forge package so it will not be in the main (continuum controlled) namespace and the build process is open.

The build seams to be working in linux and py2.7 now. We can update it to build on the other platforms once the other OS X and py3 issues are solved. Once a tag is on the git repo we are probably good to merge that conda recipe.

@wesm I added you as maintainer in the conda-forge feedstock here: https://github.com/conda-forge/staged-recipes/pull/731

**Comment by deads** [comment]
Hi @danielfrg ,

Ideally, most future versions should be backwards compatible. Hence the delay for a release tag. I will clean up the paratext import a bit, and then tag the repo. Sorry for the delay.

Best,
Damian

**Comment by danielfrg** [comment]
Not a problem I will wait for that and then finish the conda-forge recipe when its done.
